name: Test external source

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ryannogueira7926/juhal.academyatualmentes
          path: source-project
      - run: ls -la source-project
